// Generated by CoffeeScript 1.7.1
var Classifier, Tokenizer, _;

_ = require('lodash');

Tokenizer = require('code-tokenizer');

Classifier = (function() {
  function Classifier() {}

  Classifier.prototype.train = function(db, language, data) {
    var tokens;
    Tokenizer = new Tokenizer();
    tokens = Tokenizer.tokenize(data);
    db['tokens_total'] = db['tokens_total'] || 0;
    db['languages_total'] = db['languages_total'] || 0;
    db['tokens'] = db['tokens'] || {};
    db['language_tokens'] = db['language_tokens'] || {};
    db['languages'] = db['languages'] || {};
    _.each(tokens, function(token) {
      db['tokens'][language] = db['tokens'][language] || {};
      db['tokens'][language][token] = db['tokens'][language][token] || 0;
      db['tokens'][language][token] += 1;
      db['language_tokens'][language] = db['language_tokens'][language] || 0;
      db['language_tokens'][language] += 1;
      return db['tokens_total'] += 1;
    });
    db['languages'][language] = db['languages'][language] || 0;
    db['languages'][language] += 1;
    db['languages_total'] += 1;
    return db;
  };

  return Classifier;

})();

module.exports = Classifier;
